<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<UserSecretsId>aspnet-FixIT.Presentation-c1bdde3e-adfe-45b9-8468-2bcdfc7692ef</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FixIT.Application\FixIT.Application.csproj" />
    <ProjectReference Include="..\FixIT.Infrastracture\FixIT.Infrastracture.csproj" />
  </ItemGroup>

</Project>
