<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2cd89e3f-37c7-4593-bdc1-ef2f58d2e030</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FixIT.Application\FixIT.Application.csproj" />
    <ProjectReference Include="..\FixIT.Infrastracture\FixIT.Infrastracture.csproj" />
  </ItemGroup>

</Project>
